<a href="https://colab.research.google.com/github/manasamorthad/DeepLearning/blob/main/dl_week4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install tensorflow numpy

In [ ]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD,Adagrad,RMSprop,Adadelta,Adam


X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])


model = Sequential([
Dense(4,activation='relu',input_shape=(2,)),
Dense(1,activation='sigmoid')
])
#1. Batch Gradient Descent (BGD)
model.compile(optimizer=SGD(learning_rate=0.1),loss='binary_crossentropy')

model.fit(X,y,epochs=10,batch_size=4)
print(model.predict(X))


#2. Stochastic Gradient Descent (SGD)
model.compile(optimizer=SGD(learning_rate=0.1),loss='binary_crossentropy')

model.fit(X,y,epochs=10,batch_size=1)
print(model.predict(X))

#3  MINI BATCH Gradient Descent (SGD)

model.compile(optimizer=SGD(learning_rate=0.1),loss='binary_crossentropy')

model.fit(X,y,epochs=10,batch_size=2)
print(model.predict(X))

#sgd with momentum
model.compile(optimizer=SGD(learning_rate=0.1,momentum=0.9),loss='binary_crossentropy')

model.fit(X,y,epochs=10)
print(model.predict(X))


#sgd with nestrov

model.compile(optimizer=SGD(learning_rate=0.1,momentum=0.9,nesterov=True),
loss='binary_crossentropy')

model.fit(X,y,epochs=10)
print(model.predict(X))

# AdaGrad

model.compile(optimizer=Adagrad(),loss='binary_crossentropy')

model.fit(X,y,epochs=10)
print(model.predict(X))

#Rmsprop

model.compile(optimizer=RMSprop(),loss='binary_crossentropy')

model.fit(X,y,epochs=10)
print(model.predict(X))

#Ada Delta
model.compile(optimizer=Adadelta(),loss='binary_crossentropy')

model.fit(X,y,epochs=10)
print(model.predict(X))
#Adam

model.compile(optimizer=Adam(),loss='binary_crossentropy')

model.fit(X,y,epochs=10)
print(model.predict(X))


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 927ms/step - loss: 0.7317
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 619ms/step - loss: 0.7301
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.7280
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 0.7260
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 0.7241
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.7222
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.7204
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 0.7186
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.7171
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.7154
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 201ms/step
[[0.4932864 ]
 [0.53029567]
 [0.48021403]
 [0.5538899 ]]
Epoch 1/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.7639  
Epoch 2/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.7558 
Epoch 3/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.7445 
Epoch 4/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.7445
Epoc

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 193ms/step
[[0.47913274]
 [0.48800302]
 [0.691638  ]
 [0.40434596]]
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 0.5641
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.5640
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step - loss: 0.5639
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 0.5639
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step - loss: 0.5638
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - loss: 0.5638
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 0.5637
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - loss: 0.5637
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step - loss: 0.5637
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 0.5636


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 195ms/step
[[0.47896782]
 [0.48788655]
 [0.6927025 ]
 [0.40402338]]
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 802ms/step - loss: 0.5636
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.5630
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.5626
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.5622
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.5617
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 0.5613
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 0.5610
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.5610
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 0.5606
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 0.5602
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 282ms/step
[[0.47322586]
 [0.483956  ]
 [0.6904218 ]
 [0.3957054 ]]
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 0.5602
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 0.5602
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 1

In [ ]:
!pip install kaggle

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd

train = pd.read_csv("/content/drive/MyDrive/DL_datasets/sign_mnist_train.csv")
test = pd.read_csv("/content/drive/MyDrive/DL_datasets/sign_mnist_test.csv")

In [ ]:
import numpy as np

X_train = train.drop('label', axis=1).values
y_train = train['label'].values

X_test = test.drop('label', axis=1).values
y_test = test['label'].values
X_train = X_train / 255.0
X_test = X_test / 255.0
X_train = X_train[:5000]
y_train = y_train[:5000]

X_test = X_test[:1000]
y_test = y_test[:1000]

X_train = X_train.reshape(-1,784)
X_test = X_test.reshape(-1,784)
from tensorflow.keras.utils import to_categorical

y_train = to_categorical(y_train,25)
y_test = to_categorical(y_test,25)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential([
Dense(128,activation='relu',input_shape=(784,)),
Dense(64,activation='relu'),
Dense(25,activation='softmax')
])

model.compile(
optimizer='adam',
loss='categorical_crossentropy',
metrics=['accuracy']
)

model.fit(X_train,y_train,epochs=10,batch_size=64)

Epoch 1/10


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


79/79 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.1132 - loss: 3.0655
Epoch 2/10
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.2310 - loss: 2.5673
Epoch 3/10
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3440 - loss: 2.1167
Epoch 4/10
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4340 - loss: 1.8258
Epoch 5/10
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5058 - loss: 1.6510
Epoch 6/10
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5540 - loss: 1.4866
Epoch 7/10
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5810 - loss: 1.3956
Epoch 8/10
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6138 - loss: 1.2795
Epoch 9/10
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6450 - loss: 1.1831
Epoch 10/10
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6724 - loss: 1.1058


In [ ]:
from tensorflow.keras.optimizers import SGD, Adagrad, RMSprop, Adadelta, Adam

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD, Adagrad, RMSprop, Adadelta, Adam

optimizers = {
    "BGD": SGD(learning_rate=0.01),
    "SGD": SGD(learning_rate=0.01),
    "MiniBatchGD": SGD(learning_rate=0.01),
    "Momentum": SGD(learning_rate=0.01,momentum=0.9),
    "Nesterov": SGD(learning_rate=0.01,momentum=0.9,nesterov=True),
    "Adagrad": Adagrad(),
    "RMSProp": RMSprop(),
    "Adadelta": Adadelta(),
    "Adam": Adam()
}

results = {}

def create_model(optimizer):
    model = Sequential([
        Dense(128,activation='relu',input_shape=(784,)),
        Dense(64,activation='relu'),
        Dense(25,activation='softmax')
    ])
    model.compile(
        optimizer=optimizer,
        loss='categorical_crossentropy',
        metrics=['accuracy']
    )
    return model

for name,opt in optimizers.items():

    print("Training with",name)

    model = create_model(opt);

    if name == "BGD":
        batch = len(X_train)

    elif name == "SGD":
        batch = 1

    elif name == "MiniBatchGD":
        batch = 32

    else:
        batch = 32

    history = model.fit(
        X_train,
        y_train,
        epochs=5,
        batch_size=batch,
        validation_data=(X_test,y_test),
        verbose=1
    )

    loss,accuracy = model.evaluate(X_test,y_test,verbose=0)

    results[name] = accuracy

Training with BGD
Epoch 1/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.0378 - loss: 3.4557 - val_accuracy: 0.0440 - val_loss: 3.3646
Epoch 2/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.0434 - loss: 3.3907 - val_accuracy: 0.0430 - val_loss: 3.3279
Epoch 3/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.0466 - loss: 3.3474 - val_accuracy: 0.0430 - val_loss: 3.3024
Epoch 4/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.0464 - loss: 3.3163 - val_accuracy: 0.0470 - val_loss: 3.2839
Epoch 5/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.0470 - loss: 3.2932 - val_accuracy: 0.0490 - val_loss: 3.2702
Training with SGD
Epoch 1/5
5000/5000 ━━━━━━━━━━━━━━━━━━━━ 16s 3ms/step - accuracy: 0.1138 - loss: 2.9157 - val_accuracy: 0.2750 - val_loss: 2.3334
Epoch 2/5
5000/5000 ━━━━━━━━━━━━━━━━━━━━ 14s 3ms/step - accuracy: 0.2648 - loss: 2.2168 - val_accuracy: 0.2680 - val_loss: 2.1171
Epoch 3/5
5000/5000 ━━━━━━━━━━━━━━━━━━━━ 14s 3ms/step - accuracy: 0.3722 - loss: 1.8

In [ ]:
for k,v in results.items():
    print(k,"accuracy:",v)

BGD accuracy: 0.04899999871850014
SGD accuracy: 0.33500000834465027
MiniBatchGD accuracy: 0.3050000071525574
Momentum accuracy: 0.4749999940395355
Nesterov accuracy: 0.5230000019073486
Adagrad accuracy: 0.1080000028014183
RMSProp accuracy: 0.4059999883174896
Adadelta accuracy: 0.054999999701976776
Adam accuracy: 0.45899999141693115
